### PR TITLE
Proposed reorganization for asset management

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
Still a work-in-progress - I'll add some notes and mark this PR as ready for review once I'm done.

**Comment by StevenClontz** [comment]
This is certainly not reviewable by looking at the files changed, as many assets and build files were added or deleted in this process.

But here's the end result: anyone can now fork the repo, install the dependencies (which happens automatically if they use a GitHub codespace), make updates to source, and then build and deploy their book with these commands:

```bash
python scripts/update_assets.py # if assets in source/resources are updated
pretext build web
pretext build print
git add -A
git commit -m "your message here"
pretext deploy
```

I break this down further in the updated README. You can see what the project will look like if you accept the PR by going here: https://github.com/StevenClontz/EngineeringStatics/tree/asset-management

Let me know if you want to walk through these changes sometime.

**Comment by StevenClontz** [comment]
You can see if the deployment passes the eyeball test at these links:

https://stevenclontz.github.io/EngineeringStatics

https://stevenclontz.github.io/EngineeringStatics/pdf/statics.pdf

**Comment by whaynes** [comment]
Steven,

Thank you for looking at this and your changes. I will take you up on your offer to walk through the changes.  I will join the next drop-in that you host, or if you prefer, I can zoom any time 0800-1200 Eastern M-F.

Will Haynes

**Comment by StevenClontz** [comment]
I've emailed you at an @maritime.edu address to schedule a time to sync up.

**Comment by StevenClontz** [comment]
image

To get deploys working with new/modern setup.

**Comment by StevenClontz** [comment]
It's beyond the scope of this PR, but if you want to create a "home page" for your book akin to https://teambasedinquirylearning.github.io/calculus/ or http://abstract.ups.edu/ you can now write one in HTML and save it to `site/index.html` and it will appear for visitors of <https://engineeringstatics.org> (you'll want to make sure this links to e.g. <https://engineeringstatics.org/book-1.html> and maybe also <https://engineeringstatics.org/pdf/statics.pdf>).

**Comment by StevenClontz** [comment]
I forgot to turn this back into a draft, but it's now actually ready.

If you're happy with the reorganization, you should be able to select "Squash and Merge" from the green button/dropdown below. This will update your `master` branch with these changes, which you can then pull to your device to work against.

I recommend that you do a full build and deploy, then update the GitHub Pages settings as in my screenshot above to ensure `engineeringstatics.org` is indeed wired up correctly as I think it should be. Email me if you want to sync up when you do that so I can live troubleshoot if necessary.

Thanks for being a part of the community and my go-to example of an excellent PreTeXt book outside math/CS. :-)

**Pull request merged**
